version: '3.8'

services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./models:/app/models
      - ./notebooks:/app/notebooks
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=
      - JUPYTER_PASSWORD=
    command: >
      jupyter lab
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --allow-root
      --NotebookApp.token=''
      --NotebookApp.password=''
      --NotebookApp.allow_origin='*'
      --NotebookApp.disable_check_xsrf=True
    restart: unless-stopped
    networks:
      - attention-networks

  # Optional: Add a service for running tests
  test:
    build: .
    volumes:
      - .:/app
    command: >
      bash -c "
        python -m pytest tests/ -v --cov=. --cov-report=xml
      "
    depends_on:
      - jupyter
    networks:
      - attention-networks

networks:
  attention-networks:
    driver: bridge

volumes:
  data:
  models:
  notebooks:
